import { DndContext, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, rectSortingStrategy, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { read, utils } from "xlsx";
import { useRef, useState, type FormEvent } from "react";
import { useHydrated } from "@tanstack/react-router";
import { AlertCircle, CheckCircle2, ChevronDown, ChevronRight, Download, FileSpreadsheet, GripVertical, MoreHorizontal, Pencil, Plus, Search, Star, Trash2, Upload, XCircle } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { matchIndicator, normalize, useIndicators, type Group, type ImportedRow, type Indicator } from "@/lib/indicator-store";

const groupStyles: Record<string, string> = { emerald: "bg-emerald-500", cyan: "bg-cyan-500", amber: "bg-amber-500", rose: "bg-rose-500", violet: "bg-violet-500", blue: "bg-blue-500" };
const colors = Object.keys(groupStyles);

function PageTitle({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) {
  return <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-bold uppercase text-primary">{eyebrow}</p><h1 className="text-3xl font-bold">{title}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{description}</p></div>{action}</div>;
}

function SortableIndicator({ item, group, onEdit, onDelete }: { item: Indicator; group: Group; onEdit: () => void; onDelete: () => void }) {
  const { togglePriority } = useIndicators();
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: item.id, data: { type: "indicator" } });
  return <div ref={setNodeRef} style={{ transform: CSS.Transform.toString(transform), transition }} className={cn("group flex min-h-16 items-center gap-2 border-b bg-card px-3 last:border-b-0", isDragging && "z-50 opacity-50 shadow-lg")}>
    <Button variant="ghost" size="icon" className="cursor-grab text-muted-foreground" {...attributes} {...listeners} aria-describedby={undefined} aria-label={`Arrastar ${item.name}`}><GripVertical /></Button>
    <span className={cn("h-8 w-1 rounded-full", groupStyles[group.color] ?? "bg-primary")} />
    <div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.name}</p><p className="truncate text-xs text-muted-foreground">{item.unit || "Sem unidade"}{item.target !== undefined ? ` · Meta ${item.target.toLocaleString("pt-BR")}` : " · Sem meta"}</p></div>
    <Button variant="ghost" size="icon" onClick={() => togglePriority(item.id)} title={item.priority ? "Remover prioridade" : "Marcar como prioritário"} aria-label={item.priority ? "Remover prioridade" : "Marcar como prioritário"}><Star className={cn(item.priority && "fill-amber-400 text-amber-500")} /></Button>
    <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={`Ações de ${item.name}`}><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={onEdit}><Pencil /> Editar</DropdownMenuItem><DropdownMenuItem className="text-destructive" onClick={onDelete}><Trash2 /> Excluir</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
  </div>;
}

function SortableGroup({ group, items, onAdd, onEdit, onDelete, onEditIndicator, onDeleteIndicator }: { group: Group; items: Indicator[]; onAdd: () => void; onEdit: () => void; onDelete: () => void; onEditIndicator: (item: Indicator) => void; onDeleteIndicator: (item: Indicator) => void }) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: group.id, data: { type: "group" } });
  return <section ref={setNodeRef} style={{ transform: CSS.Transform.toString(transform), transition }} className={cn("overflow-hidden rounded-lg border bg-card", isDragging && "z-40 opacity-60 shadow-xl")}>
    <div className="flex min-h-16 items-center gap-3 border-b bg-muted/40 px-3">
      <Button variant="ghost" size="icon" className="cursor-grab" {...attributes} {...listeners} aria-describedby={undefined} aria-label={`Arrastar grupo ${group.name}`}><GripVertical /></Button>
      <span className={cn("h-3 w-3 rounded-sm", groupStyles[group.color] ?? "bg-primary")} /><div className="flex-1"><h2 className="font-bold">{group.name}</h2><p className="text-xs text-muted-foreground">{items.length} {items.length === 1 ? "indicador" : "indicadores"}</p></div>
      <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={`Ações do grupo ${group.name}`}><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={onEdit}><Pencil /> Editar grupo</DropdownMenuItem><DropdownMenuItem className="text-destructive" onClick={onDelete}><Trash2 /> Excluir grupo</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
    </div>
    <SortableContext items={items.map((item) => item.id)} strategy={verticalListSortingStrategy}>{items.map((item) => <SortableIndicator key={item.id} item={item} group={group} onEdit={() => onEditIndicator(item)} onDelete={() => onDeleteIndicator(item)} />)}</SortableContext>
    <Button variant="ghost" className="m-2 w-[calc(100%-1rem)] justify-start text-primary" onClick={onAdd}><Plus /> Adicionar indicador</Button>
  </section>;
}

export function StructurePage() {
  const store = useIndicators();
  const dragReady = useHydrated();
  const [groupModal, setGroupModal] = useState<{ open: boolean; group?: Group }>({ open: false });
  const [indicatorModal, setIndicatorModal] = useState<{ open: boolean; groupId?: string; item?: Indicator }>({ open: false });
  const [deleting, setDeleting] = useState<{ type: "group" | "indicator"; item: Group | Indicator } | null>(null);
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }));
  const onDragEnd = ({ active, over }: DragEndEvent) => { if (!over || active.id === over.id) return; active.data.current?.type === "group" ? store.reorderGroups(String(active.id), String(over.id)) : store.moveIndicator(String(active.id), String(over.id)); };
  return <>
    <PageTitle eyebrow="Configuração" title="Estrutura do relatório" description="Organize grupos e indicadores. Arraste pelos puxadores para alterar a sequência ou mover um indicador entre grupos." action={<Button onClick={() => setGroupModal({ open: true })}><Plus /> Novo grupo</Button>} />
    <div className="mb-5 flex items-center gap-3 rounded-md border border-primary/20 bg-primary/5 px-4 py-3 text-sm"><Star className="h-4 w-4 fill-amber-400 text-amber-500" /><span><strong>{store.indicators.filter((item) => item.priority).length} prioritários</strong> aparecem primeiro no relatório e refletem esta ordem.</span></div>
    {dragReady ? <DndContext id="structure-dnd" sensors={sensors} collisionDetection={closestCenter} onDragEnd={onDragEnd}><SortableContext items={store.groups.map((group) => group.id)} strategy={rectSortingStrategy}><div className="grid gap-5 xl:grid-cols-2">{store.groups.map((group) => <SortableGroup key={group.id} group={group} items={store.indicators.filter((item) => item.groupId === group.id)} onAdd={() => setIndicatorModal({ open: true, groupId: group.id })} onEdit={() => setGroupModal({ open: true, group })} onDelete={() => setDeleting({ type: "group", item: group })} onEditIndicator={(item) => setIndicatorModal({ open: true, item, groupId: item.groupId })} onDeleteIndicator={(item) => setDeleting({ type: "indicator", item })} />)}</div></SortableContext></DndContext> : <div className="grid gap-5 xl:grid-cols-2">{store.groups.map((group) => <section key={group.id} className="rounded-lg border bg-card p-5"><h2 className="font-bold">{group.name}</h2><p className="text-sm text-muted-foreground">{store.indicators.filter((item) => item.groupId === group.id).length} indicadores</p></section>)}</div>}
    <GroupDialog state={groupModal} onOpenChange={(open) => setGroupModal({ ...groupModal, open })} />
    <IndicatorDialog state={indicatorModal} onOpenChange={(open) => setIndicatorModal({ ...indicatorModal, open })} />
    <Dialog open={!!deleting} onOpenChange={(open) => !open && setDeleting(null)}><DialogContent><DialogHeader><DialogTitle>Excluir {deleting?.type === "group" ? "grupo" : "indicador"}?</DialogTitle><DialogDescription>{deleting?.type === "group" ? `O grupo “${deleting.item.name}” só pode ser excluído se estiver vazio.` : `O indicador “${deleting?.item.name}” será removido da estrutura.`}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleting(null)}>Cancelar</Button><Button variant="destructive" onClick={() => { if (!deleting) return; const ok = deleting.type === "group" ? store.deleteGroup(deleting.item.id) : (store.deleteIndicator(deleting.item.id), true); ok ? toast.success("Item excluído") : toast.error("Realocar os indicadores antes de excluir este grupo."); setDeleting(null); }}>Excluir</Button></DialogFooter></DialogContent></Dialog>
  </>;
}

function GroupDialog({ state, onOpenChange }: { state: { open: boolean; group?: Group }; onOpenChange: (open: boolean) => void }) {
  const store = useIndicators(); const [error, setError] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get("name")); const color = String(form.get("color")); const issue = state.group ? store.updateGroup(state.group.id, name, color) : store.addGroup(name, color); if (issue) setError(issue); else { toast.success(state.group ? "Grupo atualizado" : "Grupo criado"); onOpenChange(false); } };
  return <Dialog open={state.open} onOpenChange={onOpenChange}><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>{state.group ? "Editar grupo" : "Novo grupo"}</DialogTitle><DialogDescription>Use um nome único e uma cor para identificação visual.</DialogDescription></DialogHeader><div className="my-6 space-y-4"><div className="space-y-2"><Label htmlFor="group-name">Nome</Label><Input id="group-name" name="name" defaultValue={state.group?.name} required autoFocus />{error && <p className="text-xs text-destructive">{error}</p>}</div><div className="space-y-2"><Label>Cor</Label><div className="flex gap-2">{colors.map((color) => <label key={color} className="cursor-pointer"><input type="radio" name="color" value={color} defaultChecked={(state.group?.color ?? "emerald") === color} className="peer sr-only" /><span className={cn("block h-8 w-8 rounded-md border-2 border-transparent ring-offset-2 peer-checked:ring-2 peer-checked:ring-ring", groupStyles[color])} /></label>)}</div></div></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button type="submit">Salvar grupo</Button></DialogFooter></form></DialogContent></Dialog>;
}

function IndicatorDialog({ state, onOpenChange }: { state: { open: boolean; groupId?: string; item?: Indicator }; onOpenChange: (open: boolean) => void }) {
  const store = useIndicators(); const [error, setError] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const target = String(form.get("target")); const issue = store.saveIndicator({ id: state.item?.id, groupId: String(form.get("groupId")), name: String(form.get("name")).trim(), aliases: String(form.get("aliases")).split(",").map((v) => v.trim()).filter(Boolean), unit: String(form.get("unit")), target: target ? Number(target) : undefined, priority: form.get("priority") === "on" }); if (issue) setError(issue); else { toast.success(state.item ? "Indicador atualizado" : "Indicador criado"); onOpenChange(false); } };
  return <Dialog open={state.open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto"><form onSubmit={submit}><DialogHeader><DialogTitle>{state.item ? "Editar indicador" : "Novo indicador"}</DialogTitle><DialogDescription>Configure o nome usado para o casamento automático e os dados do relatório.</DialogDescription></DialogHeader><div className="my-6 grid gap-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label htmlFor="indicator-name">Nome</Label><Input id="indicator-name" name="name" defaultValue={state.item?.name} required />{error && <p className="text-xs text-destructive">{error}</p>}</div><div className="space-y-2 sm:col-span-2"><Label htmlFor="aliases">Apelidos na planilha</Label><Input id="aliases" name="aliases" defaultValue={state.item?.aliases.join(", ")} placeholder="Ex.: novos cadastros, aquisição nova" /><p className="text-xs text-muted-foreground">Separe variações por vírgula.</p></div><div className="space-y-2"><Label>Grupo</Label><Select name="groupId" defaultValue={state.item?.groupId ?? state.groupId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{store.groups.map((group) => <SelectItem key={group.id} value={group.id}>{group.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="unit">Unidade</Label><Input id="unit" name="unit" defaultValue={state.item?.unit} placeholder="%, R$, un" /></div><div className="space-y-2"><Label htmlFor="target">Meta</Label><Input id="target" name="target" type="number" step="any" defaultValue={state.item?.target} /></div><label className="flex items-end gap-3 pb-2 text-sm font-medium"><input type="checkbox" name="priority" defaultChecked={state.item?.priority} className="h-4 w-4 accent-current" /> Indicador prioritário</label></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button type="submit">Salvar indicador</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function ImportPage() {
  const store = useIndicators(); const fileRef = useRef<HTMLInputElement>(null); const [fileName, setFileName] = useState(""); const [reference, setReference] = useState(new Date().toISOString().slice(0, 7)); const [preview, setPreview] = useState<ImportedRow[]>([]); const [busy, setBusy] = useState(false);
  const parseFile = async (file: File) => { setBusy(true); try { const workbook = read(await file.arrayBuffer()); const data = utils.sheet_to_json<Record<string, unknown>>(workbook.Sheets[workbook.SheetNames[0]], { defval: "" }); const rows = data.map((row) => { const values = Object.values(row); const sourceName = String(row.indicador ?? row.Indicador ?? row.nome ?? row.Nome ?? values[0] ?? ""); const rawValue = row.valor ?? row.Valor ?? values[1]; const value = typeof rawValue === "number" ? rawValue : Number(String(rawValue).replace(/[^0-9,.-]/g, "").replace(",", ".")); const match = matchIndicator(sourceName, store.indicators); return { id: crypto.randomUUID(), sourceName, value: Number.isFinite(value) ? value : 0, indicatorId: match?.id }; }).filter((row) => row.sourceName); setFileName(file.name); setPreview(rows); } catch { toast.error("Não foi possível ler a planilha. Verifique as colunas."); } finally { setBusy(false); } };
  const matched = preview.filter((row) => row.indicatorId).length;
  return <><PageTitle eyebrow="Entrada de dados" title="Importar planilha" description="Envie um arquivo XLSX, XLS ou CSV. A primeira coluna deve conter o indicador e a segunda, o valor." />
    <div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-lg border bg-card p-5"><h2 className="text-lg font-bold">Nova importação</h2><p className="mt-1 text-sm text-muted-foreground">Os dados são processados e armazenados somente neste navegador.</p><div className="mt-5 space-y-4"><div className="space-y-2"><Label htmlFor="reference">Referência</Label><Input id="reference" type="month" value={reference} onChange={(e) => setReference(e.target.value)} /></div><input ref={fileRef} className="hidden" type="file" accept=".xlsx,.xls,.csv" onChange={(e) => { const file = e.target.files?.[0]; if (file) void parseFile(file); }} /><button type="button" onClick={() => fileRef.current?.click()} className="flex min-h-44 w-full flex-col items-center justify-center rounded-lg border-2 border-dashed bg-muted/30 p-6 text-center transition-colors hover:border-primary/50 hover:bg-primary/5"><Upload className="mb-3 h-7 w-7 text-primary" /><span className="font-semibold">{busy ? "Lendo planilha..." : fileName || "Selecione uma planilha"}</span><span className="mt-1 text-xs text-muted-foreground">XLSX, XLS ou CSV</span></button>{preview.length > 0 && <div className="grid grid-cols-3 gap-3"><Stat value={preview.length} label="Linhas" /><Stat value={matched} label="Casadas" tone="success" /><Stat value={preview.length - matched} label="Órfãs" tone="warning" /></div>}<Button className="w-full" disabled={!preview.length || !reference} onClick={() => { store.addImport({ id: crypto.randomUUID(), fileName, reference, importedAt: new Date().toISOString(), rows: preview }); setPreview([]); setFileName(""); toast.success("Importação concluída"); }}>Confirmar importação</Button></div></section>
      <section><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Histórico</h2><Badge variant="secondary">{store.imports.length} importações</Badge></div><div className="space-y-3">{store.imports.map((item) => <div key={item.id} className="flex items-center gap-4 rounded-lg border bg-card p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-md bg-emerald-500/10 text-emerald-600"><FileSpreadsheet /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.fileName}</p><p className="text-xs text-muted-foreground">{item.reference} · {new Date(item.importedAt).toLocaleDateString("pt-BR")}</p></div><Badge variant="outline">{item.rows.length} linhas</Badge></div>)}</div></section></div>
  </>;
}

function Stat({ value, label, tone }: { value: number; label: string; tone?: "success" | "warning" }) { return <div className={cn("rounded-md border p-3", tone === "success" && "border-emerald-500/30 bg-emerald-500/5", tone === "warning" && "border-amber-500/30 bg-amber-500/5")}><p className="text-xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>; }

function ImportSelect() { const store = useIndicators(); return <Select value={store.selectedImportId} onValueChange={store.setSelectedImportId}><SelectTrigger className="w-full sm:w-64"><SelectValue placeholder="Selecione uma importação" /></SelectTrigger><SelectContent>{store.imports.map((item) => <SelectItem key={item.id} value={item.id}>{item.reference} · {item.fileName}</SelectItem>)}</SelectContent></Select>; }

export function ConferencePage() {
  const store = useIndicators(); const selected = store.imports.find((item) => item.id === store.selectedImportId); const [openChecked, setOpenChecked] = useState(false); const [query, setQuery] = useState("");
  const checked = selected?.rows.filter((row) => row.indicatorId) ?? []; const matchedIds = new Set(checked.map((row) => row.indicatorId)); const missing = store.indicators.filter((item) => !matchedIds.has(item.id)); const unmapped = selected?.rows.filter((row) => !row.indicatorId && !row.ignored) ?? [];
  return <><PageTitle eyebrow="Auditoria" title="Conferência dos dados" description="Revise correspondências automáticas, itens sem dado e linhas ainda não mapeadas." action={<ImportSelect />} />
    {!selected ? <Empty title="Nenhuma importação selecionada" /> : <div className="space-y-4"><AuditSection title="Conferido" count={checked.length} icon={<CheckCircle2 className="text-emerald-600" />} open={openChecked} onToggle={() => setOpenChecked(!openChecked)} tone="success">{checked.map((row) => <AuditRow key={row.id} name={store.indicators.find((item) => item.id === row.indicatorId)?.name ?? row.sourceName} detail={`Origem: ${row.sourceName}`} value={row.value} />)}</AuditSection><AuditSection title="Sem dado" count={missing.length} icon={<AlertCircle className="text-amber-600" />} open tone="warning">{missing.map((item) => <AuditRow key={item.id} name={item.name} detail={store.groups.find((group) => group.id === item.groupId)?.name ?? "Sem grupo"} />)}</AuditSection><AuditSection title="Não mapeado" count={unmapped.length} icon={<XCircle className="text-destructive" />} open tone="danger">{unmapped.map((row) => <div key={row.id} className="flex flex-col gap-3 border-b p-4 last:border-0 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-semibold">{row.sourceName}</p><p className="text-xs text-muted-foreground">Valor: {row.value.toLocaleString("pt-BR")}</p></div><Select onValueChange={(id) => { store.linkRow(selected.id, row.id, id); toast.success("Linha vinculada e apelido salvo"); }}><SelectTrigger className="sm:w-64"><SelectValue placeholder="Vincular a indicador" /></SelectTrigger><SelectContent><div className="p-2"><div className="flex items-center gap-2 rounded-md border px-2"><Search className="h-4 w-4" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-8 w-full bg-transparent text-sm outline-none" placeholder="Buscar" /></div></div>{store.indicators.filter((item) => normalize(item.name).includes(normalize(query))).map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select><Button variant="ghost" onClick={() => store.ignoreRow(selected.id, row.id)}>Ignorar</Button></div>)}</AuditSection></div>}
  </>;
}

function AuditSection({ title, count, icon, open = true, onToggle, children, tone }: { title: string; count: number; icon: React.ReactNode; open?: boolean; onToggle?: () => void; children: React.ReactNode; tone: "success" | "warning" | "danger" }) { return <section className={cn("overflow-hidden rounded-lg border bg-card", tone === "success" && "border-emerald-500/30", tone === "warning" && "border-amber-500/30", tone === "danger" && "border-destructive/30")}><button type="button" className="flex w-full items-center gap-3 p-4 text-left" onClick={onToggle}>{icon}<h2 className="flex-1 font-bold">{title}</h2><Badge variant="secondary">{count}</Badge>{open ? <ChevronDown /> : <ChevronRight />}</button>{open && <div className="border-t">{count ? children : <p className="p-5 text-sm text-muted-foreground">Nenhum item nesta categoria.</p>}</div>}</section>; }
function AuditRow({ name, detail, value }: { name: string; detail: string; value?: number }) { return <div className="flex items-center gap-4 border-b p-4 last:border-0"><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{name}</p><p className="truncate text-xs text-muted-foreground">{detail}</p></div>{value !== undefined && <strong>{value.toLocaleString("pt-BR")}</strong>}</div>; }

export function ReportPage() {
  const store = useIndicators(); const selected = store.imports.find((item) => item.id === store.selectedImportId); const rowsByIndicator = new Map(selected?.rows.filter((row) => row.indicatorId).map((row) => [row.indicatorId, row]) ?? []); const priorities = store.groups.flatMap((group) => store.indicators.filter((item) => item.groupId === group.id && item.priority));
  return <><PageTitle eyebrow="Saída final" title="Relatório de indicadores" description="Prioridades consolidadas e visão completa por grupo, incluindo indicadores sem correspondência." action={<div className="flex flex-col gap-2 sm:flex-row"><ImportSelect /><Button variant="outline" onClick={() => window.print()}><Download /> Exportar PDF</Button></div>} />
    {!selected ? <Empty title="Importe dados para gerar o relatório" /> : <div className="space-y-8 print:space-y-5"><section><div className="mb-4 flex items-center gap-2"><Star className="fill-amber-400 text-amber-500" /><h2 className="text-xl font-bold">Prioritários</h2><Badge variant="secondary">{priorities.length}</Badge></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{priorities.map((item) => <ReportCard key={item.id} item={item} row={rowsByIndicator.get(item.id)} group={store.groups.find((group) => group.id === item.groupId)} priority />)}</div></section>{store.groups.map((group) => <section key={group.id}><div className="mb-3 flex items-center gap-3"><span className={cn("h-3 w-3 rounded-sm", groupStyles[group.color])} /><h2 className="text-xl font-bold">{group.name}</h2><div className="h-px flex-1 bg-border" /></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{store.indicators.filter((item) => item.groupId === group.id).map((item) => <ReportCard key={item.id} item={item} row={rowsByIndicator.get(item.id)} group={group} />)}</div></section>)}</div>}
  </>;
}

function ReportCard({ item, row, group, priority }: { item: Indicator; row?: ImportedRow; group?: Group; priority?: boolean }) { const progress = row && item.target ? Math.min(100, (row.value / item.target) * 100) : 0; const format = (value: number) => item.unit === "R$" ? value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }) : `${value.toLocaleString("pt-BR")}${item.unit === "%" ? "%" : item.unit === "un" ? "" : ` ${item.unit}`}`; return <article className={cn("rounded-lg border bg-card p-5", !row && "border-amber-500/40 bg-amber-500/5", priority && "border-primary/30")}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-muted-foreground">{group?.name}</p><h3 className="mt-1 font-bold">{item.name}</h3></div>{priority && <Star className="h-4 w-4 fill-amber-400 text-amber-500" />}</div>{row ? <><p className="mt-5 text-3xl font-bold">{format(row.value)}</p>{item.target !== undefined && <div className="mt-4"><div className="mb-2 flex justify-between text-xs"><span className="text-muted-foreground">Meta {format(item.target)}</span><strong>{Math.round(progress)}%</strong></div><Progress value={progress} /></div>}</> : <div className="mt-5 flex items-center gap-2 text-sm font-semibold text-amber-700"><AlertCircle className="h-4 w-4" /> Sem dado nesta referência</div>}</article>; }
function Empty({ title }: { title: string }) { return <div className="grid min-h-64 place-items-center rounded-lg border border-dashed bg-muted/20 p-8 text-center"><div><FileSpreadsheet className="mx-auto mb-3 h-8 w-8 text-muted-foreground" /><p className="font-semibold">{title}</p></div></div>; }