/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorcidaPremiadaRouteImport } from './routes/torcida-premiada'
import { Route as ResumoCriticosRouteImport } from './routes/resumo-criticos'
import { Route as ResumoRouteImport } from './routes/resumo'
import { Route as PaginasRouteImport } from './routes/paginas'
import { Route as Metas2qRouteImport } from './routes/metas-2q'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as AtivacoesRouteImport } from './routes/ativacoes'
import { Route as AtingimentoDddRouteImport } from './routes/atingimento-ddd'
import { Route as IndexRouteImport } from './routes/index'

const TorcidaPremiadaRoute = TorcidaPremiadaRouteImport.update({
  id: '/torcida-premiada',
  path: '/torcida-premiada',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumoCriticosRoute = ResumoCriticosRouteImport.update({
  id: '/resumo-criticos',
  path: '/resumo-criticos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumoRoute = ResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginasRoute = PaginasRouteImport.update({
  id: '/paginas',
  path: '/paginas',
  getParentRoute: () => rootRouteImport,
} as any)
const Metas2qRoute = Metas2qRouteImport.update({
  id: '/metas-2q',
  path: '/metas-2q',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivacoesRoute = AtivacoesRouteImport.update({
  id: '/ativacoes',
  path: '/ativacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtingimentoDddRoute = AtingimentoDddRouteImport.update({
  id: '/atingimento-ddd',
  path: '/atingimento-ddd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atingimento-ddd': typeof AtingimentoDddRoute
  '/ativacoes': typeof AtivacoesRoute
  '/metas': typeof MetasRoute
  '/metas-2q': typeof Metas2qRoute
  '/paginas': typeof PaginasRoute
  '/resumo': typeof ResumoRoute
  '/resumo-criticos': typeof ResumoCriticosRoute
  '/torcida-premiada': typeof TorcidaPremiadaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atingimento-ddd': typeof AtingimentoDddRoute
  '/ativacoes': typeof AtivacoesRoute
  '/metas': typeof MetasRoute
  '/metas-2q': typeof Metas2qRoute
  '/paginas': typeof PaginasRoute
  '/resumo': typeof ResumoRoute
  '/resumo-criticos': typeof ResumoCriticosRoute
  '/torcida-premiada': typeof TorcidaPremiadaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atingimento-ddd': typeof AtingimentoDddRoute
  '/ativacoes': typeof AtivacoesRoute
  '/metas': typeof MetasRoute
  '/metas-2q': typeof Metas2qRoute
  '/paginas': typeof PaginasRoute
  '/resumo': typeof ResumoRoute
  '/resumo-criticos': typeof ResumoCriticosRoute
  '/torcida-premiada': typeof TorcidaPremiadaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atingimento-ddd'
    | '/ativacoes'
    | '/metas'
    | '/metas-2q'
    | '/paginas'
    | '/resumo'
    | '/resumo-criticos'
    | '/torcida-premiada'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atingimento-ddd'
    | '/ativacoes'
    | '/metas'
    | '/metas-2q'
    | '/paginas'
    | '/resumo'
    | '/resumo-criticos'
    | '/torcida-premiada'
  id:
    | '__root__'
    | '/'
    | '/atingimento-ddd'
    | '/ativacoes'
    | '/metas'
    | '/metas-2q'
    | '/paginas'
    | '/resumo'
    | '/resumo-criticos'
    | '/torcida-premiada'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtingimentoDddRoute: typeof AtingimentoDddRoute
  AtivacoesRoute: typeof AtivacoesRoute
  MetasRoute: typeof MetasRoute
  Metas2qRoute: typeof Metas2qRoute
  PaginasRoute: typeof PaginasRoute
  ResumoRoute: typeof ResumoRoute
  ResumoCriticosRoute: typeof ResumoCriticosRoute
  TorcidaPremiadaRoute: typeof TorcidaPremiadaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torcida-premiada': {
      id: '/torcida-premiada'
      path: '/torcida-premiada'
      fullPath: '/torcida-premiada'
      preLoaderRoute: typeof TorcidaPremiadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumo-criticos': {
      id: '/resumo-criticos'
      path: '/resumo-criticos'
      fullPath: '/resumo-criticos'
      preLoaderRoute: typeof ResumoCriticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumo': {
      id: '/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof ResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paginas': {
      id: '/paginas'
      path: '/paginas'
      fullPath: '/paginas'
      preLoaderRoute: typeof PaginasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas-2q': {
      id: '/metas-2q'
      path: '/metas-2q'
      fullPath: '/metas-2q'
      preLoaderRoute: typeof Metas2qRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativacoes': {
      id: '/ativacoes'
      path: '/ativacoes'
      fullPath: '/ativacoes'
      preLoaderRoute: typeof AtivacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atingimento-ddd': {
      id: '/atingimento-ddd'
      path: '/atingimento-ddd'
      fullPath: '/atingimento-ddd'
      preLoaderRoute: typeof AtingimentoDddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtingimentoDddRoute: AtingimentoDddRoute,
  AtivacoesRoute: AtivacoesRoute,
  MetasRoute: MetasRoute,
  Metas2qRoute: Metas2qRoute,
  PaginasRoute: PaginasRoute,
  ResumoRoute: ResumoRoute,
  ResumoCriticosRoute: ResumoCriticosRoute,
  TorcidaPremiadaRoute: TorcidaPremiadaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
